services:
  postgres:
    image: postgres:16-alpine
    container_name: interview-postgres
    environment:
      POSTGRES_DB: interview
      POSTGRES_USER: interview
      POSTGRES_PASSWORD: interview
    ports:
      - "8400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./articles.csv:/docker-entrypoint-initdb.d/articles.csv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interview"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

